<h4>15 Numpy</h4>
<h5>> NumPy is a Python library used for working with arrays.
<br/>> It also has functions for working in domain of linear algebra, fourier transform, and matrices.
<br/>> NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
<br/>> NumPy stands for Numerical Python.
<br/>> In Python we have lists that serve the purpose of arrays, but they are slow to process.
<br/>> NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
<br/>> The array object in NumPy is called "ndarray", it provides a lot of supporting functions that make working with "ndarray" very easy.
<br/>> Arrays are very frequently used in data science, where speed and resources are very important.
<br/>> NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
<br/>> This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.
<br/>> We can install Numpy using the following command in the command prompt: 
<br/> >>> pip install numpy
<br/>> For using numpy we need to use the following statement: 
<br/> >>> import numpy or import numpy as np
</h5>

In [ ]:
# for installing numpy (only to be run once)
pip install numpy

In [11]:
# Creating a numpy array from a list
import numpy as np
ar=np.array([1,2,3,"A","B"])
print(ar,type(ar))
# Creating a numpy array from a tuple
ar=np.array((10,20,30,"A","B"))
print(ar,type(ar))

['1' '2' '3' 'A' 'B'] <class 'numpy.ndarray'>
['10' '20' '30' 'A' 'B'] <class 'numpy.ndarray'>


<h4>01 Dimensions in a Numpy array</h4>
<h5>> A dimension in arrays is one level of array depth (nested arrays).
<br/>> We can create Numpy arrays with any number of dimensions.
<br/>> 0-D Arrays: Also known as Scalars, are the elements in an array. Each value in an array is a 0-D array.
<br/>> 1-D Arrays: An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays.
<br/>> 2-D Arrays: An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors.
</h5>

In [21]:
# 0-D Array
import numpy as np
ar=np.array(100) # ar is now a 0-D array so we cannot use for-in loop
print(ar)
# 1-D Array
ar=np.array([1,2,3,4,5]) 
# we can use for-in loop to access individual elements
print(ar)
for n in ar:
    print(n,end=" ")
# 2-D Array
print()
ar=np.array([[1,2,3,4,5],["A","B","C","D","E"]])
for n in ar:
    print(n)

100
[1 2 3 4 5]
1 2 3 4 5 
['1' '2' '3' '4' '5']
['A' 'B' 'C' 'D' 'E']


<h4>02 Checking the number of dimensions</h4>
<h5> We can know the number of dimensions using "ndim" attribute
</h5>

In [25]:
# using "ndim" attribute
import numpy as np
a=np.array(100)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print("a.ndim=",a.ndim)
print("b.ndim=",b.ndim)
print("c.ndim=",c.ndim)
print("d.ndim=",d.ndim)

a.ndim= 0
b.ndim= 1
c.ndim= 2
d.ndim= 3


<h4>03 Indexing in Numpy arrays</h4>
<h5>> We use [index] to access the numpy array elements
<br/>> We can use [row,col] notation also when accessing 2-D array elements
<br/>> We can use +ve as well as -ve indexing
</h5>

In [32]:
import numpy as np
ar=np.array([1,2,3,4])
print(ar)
print(ar[3]) # 4
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar[1,2]) # 6
ar=np.array([1,2,3,4])
i=0
n=len(ar)
for i in range(n):
    print("ar[{}] or [{}] = {}".format(i,i-n,ar[i]))

[1 2 3 4]
4
6
ar[0] or [-4] = 1
ar[1] or [-3] = 2
ar[2] or [-2] = 3
ar[3] or [-1] = 4


<h4>04 Slicing in Numpy arrays</h4>
<h5>> While slicing 2-D arrays we need to use the following notation:
<br/>> ndarray[row,col]
<br/>> ndarray[rowindexstart : rowindexend, colindexstart : colindexend]
</h5>

In [2]:
import numpy as np
ar=np.array(range(1,10))
print(ar) #[1 2 3 4 5 6 7 8 9]
print(ar[1:5:1]) #[2 3 4 5]
l1=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
ar=np.array(l1)
#slicing bottom four elements [[5,6][8,9]]
print(ar[1:3,1:3])

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[[5 6]
 [8 9]]


<h4>05 Data Types in NumPy</h4>
<h5>We can specify the data type of the elements inserted in a Numpy array
<br/> Following are some data types that we can use with Numpy arrays:
<br/> >>> int - integer
<br/> >>> bool - boolean
<br/> >>> float - float
<br/> >>> object - object
<br/> >>> str - string
<br/> Syntax: numpy.array(collection_object,dtype=data_type_name)
</h5>

In [25]:
# Using a list of integers and 'dtype' to convert the list elements
# into string and then create the numpy array 
import numpy as np
l1=[1,2,3,4,5]
ar1=np.array(l1,dtype=str)
print(ar1,ar1.dtype)
print(type(ar1[0]))

['1' '2' '3' '4' '5'] <U1
<class 'numpy.str_'>


<h4>06 Using astype() to convert data types</h4>
<h5>> We can change the data type of the elements of an existing Numpy array to other data type using astype()
<br/>> Syntax: new_array=numpy_array.astype(new_data_type_name)
</h5>

In [41]:
import numpy as np
l1=[10,20,30,40,50]
ar1=np.array(l1)
print(ar1,ar1.dtype)
ar2=ar1.astype(str)
print(ar2,ar2.dtype)
ar3=ar1.astype("float")
print(ar3,ar3.dtype)

[10 20 30 40 50] int32
['10' '20' '30' '40' '50'] <U11
[10. 20. 30. 40. 50.] float64


<h4>07 Shallow copy and Deep copy</h4>
<h5>Shallow copy: changes done to either objects are relfected on both objects as both are reference to same memory location.Shallow copy can be created as follows:
<br/>>>> numpy_array_copy=numpy_array_original
<br/>>>> numpy_array_copy=numpy_array_original.view()
<br>>>>>> when using view() although the addresses of original and copy objects are different, even then the changes take place is both.
<br/>Deep copy: changes done to one object is not reflected in other as their addresses are different. Deep copy can be created as follows:
<br/>>>> numpy_array_copy=nump_array_original.copy()
<br/>>>> numpy_array_copy=numpy.array(nump_array_original)
</h5>

In [69]:
# Shallow copy using assignment operator as well as view()
import numpy as np
ar1=np.array([1,2,3,4,5])
ar2=ar1 # shallow copy
ar3=ar1.view() # shallow copy
print("id(ar1)=",id(ar1),"id(ar2)=",id(ar2))
print("id(ar1)=",id(ar1),"id(ar3)=",id(ar3)) 
# addresses are different but both are connected
ar2[0]=111 # changes done in ar2 is reflected in ar1,ar2 and ar3
print(ar1,ar2,ar3)

id(ar1)= 2363099557264 id(ar2)= 2363099557264
id(ar1)= 2363099557264 id(ar3)= 2363225558352
[111   2   3   4   5] [111   2   3   4   5] [111   2   3   4   5]


In [67]:
# Deep copy using numpy.array() and copy() methods
import numpy as np
ar1=np.array([10,20,30,40,50])
ar2=np.array(ar1) # deep copy
ar3=ar1.copy() # deep copy
print(id(ar1),id(ar2),id(ar3)) # all addresses are different
ar1[0]=111 # changes done in ar1 is not reflected in ar2 and ar3
print(ar1,ar2,ar3)
ar2[0]=222 # changes done in ar2 is not reflected in ar1 and ar3
print(ar1,ar2,ar3)
ar3[0]=333 # changes done in ar3 is not reflected in ar1 and ar2
print(ar1,ar2,ar3)

2363225566992 2363225571216 2363225570256
[111  20  30  40  50] [10 20 30 40 50] [10 20 30 40 50]
[111  20  30  40  50] [222  20  30  40  50] [10 20 30 40 50]
[111  20  30  40  50] [222  20  30  40  50] [333  20  30  40  50]


<h4>08 shape: to view the dimensions of a Numpy array</h4>
<h5>> shape property helps us to get the dimensions of the numpy array
<br/>> It returns a tuple where number of elements in the tuple represents the number of dimensions and each element in the tuple represents number of elements present in each dimension
</h5>

In [82]:
import numpy as np
ar1=np.array([10,20,30])
print(ar1)
print(ar1.shape) 
# (3,) it means there is only 1 dimension and there are 3 elements
# in that dimension
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2)
print(ar2.shape)
# (3, 3) it means there are 2 dimensions and 
# in each dimension there are 3 elements each

[10 20 30]
(3,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


<h4>09 reshape(): to change the dimensions of a Numpy array</h4>
<h5>reshape() returns a numpy array with specified dimensions
<br/>>> It can take virtually any number of arguments
<br/>>> Each input argument can only be integer value
<br/>>> The number of input arguments represents the number of dimensions and argument value represents number of elements present in each dimension
<br/>>> The product of the input arguments should be equal to the number elements present in the numpy array object or else reshaping will not work
<br/>>> We can provide -1 to only one of the dimensions, so that python by itself can decide the number of elements for that dimension
<br/>>> If we are using only one dimension and put its value to -1 then the multi-dimension array is flattened to a single dimension array
</h5>

In [91]:
# Using reshape() to build a 3x3 array from an array of 9 elements
import numpy as np
ar1=np.array([1,2,3,4,5,6,7,8,9])
print(ar1)
print(ar1.shape)
# (9,) there is only 1 dimension with 9 elements
ar2=ar1.reshape(3,3) 
# calling reshape() returns the reshaped object
# reshaping ar1 to have 2 dimensions and
# there will be 3 elements in each dimension
print(ar2,ar2.shape)


[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [95]:
# Using -1 as a dimension value in reshape()
import numpy as np
ar1=np.array([1,2,3,4,5,6,7,8,9])
print(ar1,ar1.shape)
ar2=ar1.reshape(3,-1)
# while reshaping python will use 3 as the second argument as
# we have specified it as -1
print(ar2,ar2.shape)
ar3=ar2.reshape(-1) # flattening the array to single dimension
print(ar3,ar3.shape)

[1 2 3 4 5 6 7 8 9] (9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
[1 2 3 4 5 6 7 8 9] (9,)


<h4>10 Iterating through a Numpy array</h4>
<h5>> In a multi dimension array we need nested for loops to iterate through each element in a multi-dimensional array
<br/>> We can use nditer(numpy_array) method to iterate through each element in a mutli-dimensional array using a single for loop
</h5>

In [104]:
import numpy as np
ar1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(ar1.shape)
for n in ar1: # the array is accessed row wise
    print(n)
for n in np.nditer(ar1): # individual elements are accessed
    print(n)

(3, 3)
[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


<h4>11(a) Joining Numpy arrays</h4>
<h5>> Using: concatenate((ar1,ar2,...,arn),axis=0)
<br/>>> Join a sequence of arrays along an existing axis.
<br/>>> Concatenation can only be done with arrays with same dimensions.
<br/> >>> If axis is None,arrays are flattened before use. Default is 0.
<br/>>>> axis=0 for concatenating vertically (row-wise) (by default), here the number of columns in all the source arrays should be same. 
<br/>>>>>> In the resultant array the number of rows will increase but the number columns will remain the same.
<br/>>>> axis=1 for concatenating horizontally (column-wise), here the number of rows in all the source arrays should be same.
<br/>>>>>> In the resultant array the number of columns will increase but the number rows will remain the same.
</h5>

In [9]:
# Concatenating 1-D array of same dimension but different sizes
import numpy as np
ar1=np.array([10,20,30])
ar2=np.array([40,50,60,70])
print("ar1: ",ar1.ndim,ar1.shape)
print("ar2: ",ar2.ndim,ar2.shape)
# same dimensions but different shapes
ar3=np.concatenate((ar1,ar2))
print(ar3)

ar1:  1 (3,)
ar2:  1 (4,)
[10 20 30 40 50 60 70]


In [26]:
# Using concatenate() function for vertical stacking
# axis=0 for concatenating vertically (row-wise) (by default), 
# here the number of columns in all the source arrays should be same.
import numpy as np
l1=[
    [1,2,3,4],
    [5,6,7,8]
]
l2=[
    [10,20,30,40]
]
ar1=np.array(l1)
ar2=np.array(l2)
print("ar1: ",ar1.ndim,ar1.shape)
print("ar2: ",ar2.ndim,ar2.shape)
ar3=np.concatenate((ar1,ar2),axis=0) 
# axis=0 for conctenating vertically (by default)
# so the number of columns in ar1 and ar2 should be same
print("ar3: ",ar3.ndim,ar3.shape)
print(ar3)
# in result number of columns are same but number rows have increased

ar1:  2 (2, 4)
ar2:  2 (1, 4)
ar3:  2 (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]]


In [25]:
# Using concatenate() function for horizontal stacking
# axis=1 for concatenating horizontally (column-wise), 
# here the number of rows in all the source arrays should be same.
import numpy as np
l1=[
    [1,2,3,4],
    [5,6,7,8]
]
l2=[
    [10,20],
    [30,40]
]
ar1=np.array(l1)
ar2=np.array(l2)
print("ar1: ",ar1.ndim,ar1.shape)
print("ar2: ",ar2.ndim,ar2.shape)
ar3=np.concatenate((ar1,ar2),axis=1) 
# axis=1 for conctenating horizontally
# so the number of rows in ar1 and ar2 should be same
print("ar3: ",ar3.ndim,ar3.shape)
print(ar3)
# in result number of rows are same but number columns have increased

ar1:  2 (2, 4)
ar2:  2 (2, 2)
ar3:  2 (2, 6)
[[ 1  2  3  4 10 20]
 [ 5  6  7  8 30 40]]


<h4>11(b) Joining Numpy arrays</h4>
<h5>> Using: stack((ar1,ar2,...),axis=0)
<br/>>> Join a sequence of arrays along a new axis of the resultant array
<br/>>> The dimensions and shape of the source arrays should be exactly same
<br/>>> The resultant stacked array has one more dimension than the source arrays
<br/>>>> axis=0: it performs column-wise pairing (by default)
<br/>>>>>> taking each vertical column at a time from each array and place them column-wise in the resultant array
<br/>>>> axis=1: it performs row-wise pairing
<br/>>>>>> taking each horizontal row at a time from each array and place them row-wise in the resultant array
</h5>

In [38]:
# Using stack() function for stacking 1-D arrays
# The resultant array will be a 2-D array (source dimension + 1 dimension)
# axis=0 it performs column-wise pairing (by default)
# taking each vertical column at a time from each array and 
# place them column-wise in the resultant array
import numpy as np
ar1=np.array([10,20,30])
ar2=np.array([40,50,60])
print("ar1: ",ar1.ndim,ar1.shape)
print("ar2: ",ar2.ndim,ar2.shape)
ar3=np.stack((ar1,ar2)) # axis=0
print("ar3: ",ar3.ndim,ar3.shape)
print(ar3)

ar1:  1 (3,)
ar2:  1 (3,)
ar3:  2 (2, 3)
[[10 20 30]
 [40 50 60]]


In [37]:
# Using stack() function for stacking 2-D arrays
# axis=0: it performs column-wise pairing 
# taking each vertical column at a time from each array 
# and place them column-wise in the resultant array
# dimensions and shape of source arrays should be same
import numpy as np
l1=[
    [1,2,3,4],
    [5,6,7,8]
]
l2=[
    [10,20,30,40],
    [50,60,70,80],
]
ar1=np.array(l1)
ar2=np.array(l2)
print("ar1: ",ar1.ndim,ar1.shape)
print("ar2: ",ar2.ndim,ar2.shape)
ar3=np.stack((ar1,ar2),axis=0) 
print("ar3: ",ar3.ndim,ar3.shape)
print(ar3)

ar1:  2 (2, 4)
ar2:  2 (2, 4)
ar3:  3 (2, 2, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [50 60 70 80]]]


In [32]:
# Using stack() for 2-D arrays
# axis=1: it performs row-wise pairing
# taking each horizontal row at a time from each array and 
# place them row-wise in the resultant array
l1=[
    [1,2,3,4],
    [5,6,7,8]
]
l2=[
    [10,20,30,40],
    [50,60,70,80],
]
ar1=np.array(l1)
ar2=np.array(l2)
print("ar1: ",ar1.ndim,ar1.shape)
print("ar2: ",ar2.ndim,ar2.shape)
ar3=np.stack((ar1,ar2),axis=1)
print("ar3: ",ar3.ndim,ar3.shape)
print(ar3)

ar1:  2 (2, 4)
ar2:  2 (2, 4)
ar3:  3 (2, 2, 4)
[[[ 1  2  3  4]
  [10 20 30 40]]

 [[ 5  6  7  8]
  [50 60 70 80]]]


<h4>11(c) Joining Numpy arrays</h4>
<h5>> Using: hstack((ar1,ar2,...))
<br/>>> Stack arrays in sequence horizontally (column wise)
<br/>>> All the source arrays should be of same number of rows.
<br/>>> Each row from each source array is arranged from left to right and placed in the resultant array
</h5>

In [3]:
# Using hstack() to stack along rows on 1-D array
import numpy as np
ar1=np.array([10,20,30])
ar2=np.array([40,50,60])
print("ar1=",ar1.ndim,ar1.shape)
print(ar1)
print("ar2=",ar2.ndim,ar2.shape)
print(ar2)
ar3=np.hstack((ar1,ar2))
print("ar3=",ar3.ndim,ar3.shape)
print(ar3)

ar1= 1 (3,)
[10 20 30]
ar2= 1 (3,)
[40 50 60]
ar3= 1 (6,)
[10 20 30 40 50 60]


In [12]:
# Using hstack() to stack along rows on 2-D array
import numpy as np
l1=[
    [1,2,3,100],
    [4,5,6,200]
]
l2=[
    [7,8,9],    
    [10,11,12],
]
ar1=np.array(l1)
ar2=np.array(l2)
print("ar1=",ar1.ndim,ar1.shape)
print(ar1)
print("ar2=",ar2.ndim,ar2.shape)
print(ar2)
ar3=np.hstack((ar1,ar2))
print("ar3=",ar3.ndim,ar3.shape)
print(ar3)

ar1= 2 (2, 4)
[[  1   2   3 100]
 [  4   5   6 200]]
ar2= 2 (2, 3)
[[ 7  8  9]
 [10 11 12]]
ar3= 2 (2, 7)
[[  1   2   3 100   7   8   9]
 [  4   5   6 200  10  11  12]]


<h4>11(d) Joining Numpy arrays</h4>
<h5>> Using: vstack((ar1,ar2,...))
<br/>>> Stack arrays in sequence vertically (row wise).
<br/>>> All the source arrays should be of same number of columns.
<br/>>> Each entire source array is arranged from top to bottom and placed in the resultant array
</h5>

In [15]:
# Using vstack() to stack along rows on 1-D array
import numpy as np
ar1=np.array([10,20,30])
ar2=np.array([40,50,60])
print("ar1=",ar1.ndim,ar1.shape)
print(ar1)
print("ar2=",ar2.ndim,ar2.shape)
print(ar2)
ar3=np.vstack((ar1,ar2))
print("ar3=",ar3.ndim,ar3.shape)
print(ar3)

ar1= 1 (3,)
[10 20 30]
ar2= 1 (3,)
[40 50 60]
ar3= 2 (2, 3)
[[10 20 30]
 [40 50 60]]


In [18]:
# Using vstack() to stack along rows on 2-D array
import numpy as np
l1=[
    [1,2,3],
    [4,5,6],
    [100,200,300]
]
l2=[
    [7,8,9],    
    [10,11,12],
]
ar1=np.array(l1)
ar2=np.array(l2)
print("ar1=",ar1.ndim,ar1.shape)
print(ar1)
print("ar2=",ar2.ndim,ar2.shape)
print(ar2)
ar3=np.vstack((ar1,ar2))
print("ar3=",ar3.ndim,ar3.shape)
print(ar3)

ar1= 2 (3, 3)
[[  1   2   3]
 [  4   5   6]
 [100 200 300]]
ar2= 2 (2, 3)
[[ 7  8  9]
 [10 11 12]]
ar3= 2 (5, 3)
[[  1   2   3]
 [  4   5   6]
 [100 200 300]
 [  7   8   9]
 [ 10  11  12]]


<h4>12 Splitting Numpy arrays</h4>
<h5>> Using: numpy.array_split(array,number_of_splits,axis=0)
<br/>>> Split an array into multiple sub-arrays
<br/>>> It returns a list of numpy arrays (ndarray)
<br/>>> If number of splits are more than the number of elements in the source array then it inserts empty ndarrays in the resultant list
<br/>>> axis=0 (default), it splits along columns, in 2-D arrays all the column elements from each row is considered while creating the splits
<br/>>> axis=1 , it splits along rows, in 2-D arrays all the row elements along each column is considered while creating the splits 
</h5>

In [38]:
# Using array_split() to split a 1-D array
import numpy as np
ar1=np.array([1,2,3,4,5,6,7,8,9])
print("ar1=",ar1.ndim,ar1.shape)
print(ar1)
ar2=np.array_split(ar1,4)
print(ar2,type(ar2))

ar1= 1 (9,)
[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])] <class 'list'>


In [32]:
# Using array_split() to split a 2-D array with axis=0
import numpy as np
l1=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
ar1=np.array(l1)
print("ar1=",ar1.ndim,ar1.shape)
print(ar1)
ar2=np.array_split(ar1,2)
print(ar2,type(ar2))

ar1= 2 (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])] <class 'list'>


In [35]:
# Using array_split() to split a 2-D array with axis=1
import numpy as np
l1=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
ar1=np.array(l1)
print("ar1=",ar1.ndim,ar1.shape)
print(ar1)
ar2=np.array_split(ar1,2,axis=1)
print(ar2,type(ar2))

ar1= 2 (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[3],
       [6],
       [9]])] <class 'list'>


<h4>13 Searching in Numpy arrays</h4>
<h5>> Using: numpy.where(condition_using_numpy_array)
<br/>>> Searching the numpy array for values
<br/>>> It returns a tuple containing the indexes where the search result has come true
<br/>>> For 2-D arrays it returns the intersection points of row and column indexes where the conditions are met in the 2-D array
</h5>

In [41]:
# Using where() to perform searching in 1-Darray
import numpy as np
l1=[1,2,3,4,5,6,7,8,9]
ar1=np.array(l1)
print("ar1=",ar1.ndim,ar1.shape)
print(ar1)
res=np.where(ar1%2==0) #searching for even values in ar1
print(res,type(res))

ar1= 1 (9,)
[1 2 3 4 5 6 7 8 9]
(array([1, 3, 5, 7], dtype=int64),) <class 'tuple'>


In [43]:
# Using where() to perform searching in 2-D array
import numpy as np
l1=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
ar1=np.array(l1)
print("ar1=",ar1.ndim,ar1.shape)
print(ar1)
res=np.where(ar1==5)
print(res,type(res))

ar1= 2 (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([1], dtype=int64), array([1], dtype=int64)) <class 'tuple'>


<h4>14 Sorting in Numpy arrays</h4>
<h5>> Using: sort(array,kind)
<br/>>> Sorts the array in ascending order
<br/>>> "kind" is the sorting algorithm used, any of the following types can be specified: 'quicksort', 'mergesort', 'heapsort', 'stable'
<br/>>> The default is kind='quicksort'
</h5>

In [48]:
# Using numpy.sort() to sort an array
import numpy as np
ar1=np.array([10,9,8,7])
print(ar1)
ar1.sort()
print(ar1)

[10  9  8  7]
[ 7  8  9 10]


<h4>15 Applying filter on Numpy arrays</h4>
<h5>> Applying a filter would return an array of only those elements where the filter condition is satisfied
<br/>>> We first create a list of boolean values L1 and use that list object with the array, i.e array[L1], this would generate a array of only those elements on whose index positions boolean True is present in the list L1
<br/>>> We can create a boolean list from an array by using conditional operator on the array and store the resultant list containing boolean values in a list object.
</h5>

In [55]:
# Applying filter on array
import numpy as np
l1=[True,False,True,False,True]
print(l1,type(l1))
ar1=np.array([1,2,3,4,5])
print(ar1,type(ar1))
ar2=ar1[l1]
print(ar2,type(ar2))
ar3=ar1>2
print(ar3,type(ar3))

[True, False, True, False, True] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[1 3 5] <class 'numpy.ndarray'>
[False False  True  True  True] <class 'numpy.ndarray'>


<h4>16 Random Numbers in NumPy</h4>
<h5>> NumPy offers the random module to work with random numbers.
<br>> code: from numpy import random
<hr/>
<br/>> (i) random.randint(low, high=None, size=None)
<br/>> Returns random integers from `low` (inclusive) to `high` (exclusive).
</h5>

In [6]:
# Using random.randint(low, high=None, size=None)
import numpy as np
from numpy import random
# generating one random integer number between 0 and 19
print(random.randint(20))
# generating a list of 10 random integers between 0 and 19
print(random.randint(low=0,high=20,size=10))
# generating a two dimensional list of 9 random integers between 0 to 19
print(random.randint(low=0,high=20,size=(3,3)))

19
[ 6 17 13 15  1  9 10  0 12  5]
[[18  3 16]
 [ 8  4 18]
 [10  0  5]]


<h5>> (ii) random.rand(d0,d1,...dn)
<br/>> Returns a random float value from 0 to 1
<br/>> We can specify the numnber of elements to be generated
</h5>

In [10]:
import numpy
from numpy import random
# generating one random floating point number from 0 to 1 
print(random.rand())
# generating one random floating point number from 0 to 1 
# a list of 'n' number of elements
print(random.rand(5))
# generating one random floating point number from 0 to 1 
# a list of 'n x m' elements
print(random.rand(3,3))

0.9795662737927455
[0.68611811 0.61400313 0.50764958 0.88279581 0.71209232]
[[0.53657014 0.33633317 0.12553613]
 [0.01199755 0.66786174 0.31036203]
 [0.95227151 0.39982013 0.44062707]]


<h5>> (iii) random.choice(list,size=None)
<br/>> Returns a randomly selected value from the given list
</h5>

In [18]:
import numpy
from numpy import random
l1=[10,20,30,40,50,60,70,80,90]
# selecting any one number randomly from the list l1
print(random.choice(l1))
# selecting numbers randomly from the list l1 and forming a 2x2 list
print(random.choice(l1,size=(2,2)))

70
[[60 50]
 [10 50]]
